sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pp9119/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pp9119/react-test npm test

after_success:
  - docker build -t pp9119/multi-client ./client
  - docker build -t pp9119/multi-nginx ./nginx
  - docker build -t pp9119/multi-server ./server
  - docker build -t pp9119/multi-worker ./worker
  # Log in to the docker CLI
#  - echo "$DOCKER_MY_PASSWORD" | docker login -u "$DOCKER_MY_ID" --password-stdin
  - echo "$DOCKER_MY_PASSWORD" | docker login -u "$DOCKER_MY_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pp9119/multi-client
  - docker push pp9119/multi-nginx
  - docker push pp9119/multi-server
  - docker push pp9119/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-464667472885'
  bucket_path: 'docker-multi'

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
